## 端口
server:
  port: 22100
## 服务名称
spring:
  application:
    name: xc‐service‐base‐filesystem
  data:
    ## mongodb数据库配置
    mongodb:
      database: xc_fs
      #      uri: mongodb://localhost:27017
      uri: mongodb://192.168.200.128:27017
  ##  SpringMVC上传文件配置
  servlet:
    multipart:
      # 默认支持文件上传.
      enabled: true
      #支持文件写入磁盘.
      file‐size‐threshold: 0
      # 上传文件的临时目录
      location:
      # 最大支持文件大小
      max‐file‐size: 1MB
      # 最大支持请求大小
      max‐request‐size: 30MB
## 日志
logging:
  level:
    org:
      springframework:
        boot:
          autoconfigure: error

## 文件服务器参数配置
kikock:
  fastdfs:
    connect_timeout_in_seconds: 5
    network_timeout_in_seconds: 30
    charset: UTF‐8
    tracker_servers: 192.168.200.128:22122
