server:
  port: 31000
spring:
  application:
    name: xc‐service‐manage‐cms‐client
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: xc_cms
  freemarker:
    cache: false #关闭模板缓存，方便测试
    settings:
      template_update_delay: 0
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    virtualHost: /
logging:
  level:
    org:
      springframework:
        boot:
          autoconfigure: error
xuecheng:
  mq:
    #cms客户端监控的队列名称（不同的客户端监控的队列不能重复）
    queue: queue_cms_postpage_01  #队列名称
    routingKey: 6017be4fd21800001d007e32 #消息对象名称(此routingKey为门户站点ID(PS:多个门户站点id相同))
